"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['game.py']
DATA_FILES = ["maze1.csv", "maze2.csv"]
OPTIONS = {'iconfile':'maze.png',}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
